try{
    console.log('hello');
    console.log(a);
    console.log('end of try block')
}
catch(err){
    console.log('handeled - ', err);

}
finally{
 console.log('finally');
}

console.log('end');